apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-${VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: hello-app
        version: ${VERSION}
    spec:
      containers:
        - name: hello-app
          image: phongmx/hello:${VERSION}
          ports:
          - containerPort: 80