apiVersion: v1
kind: Service
metadata:
  name: capstone-app-green
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: capstone-app
    version: ${VERSION}
  type: LoadBalancer
