apiVersion: v1
kind: Service
metadata:
  name: hello_app-green
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hello_app
    version: ${VERSION}
  type: LoadBalancer
