apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello_application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello_application
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: hello_application
        version: ${VERSION}
    spec:
      containers:
        - name: hello_application
          image: phongmx/hello:${VERSION}
          ports:
            - containerPort: 80
